version: '3.7'

services:

  mysql:
    image: mysql:8.0-oracle
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 33069:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - laravel

  webserver:
    image: php:8-apache-bullseye
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - laravel

networks:
  laravel:
